# .circleci/config.yml
version: 2.1
jobs:
  swiftlint:
    docker:
      - image: dantoml/swiftlint:latest
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: swiftlint lint --reporter junit | tee result.xml
      - store_artifacts:
          path: result.xml
      - store_test_results:
          path: result.xml
  
  build-and-test:
    macos:
      xcode: 13.4.1
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: custom_lane # $FASTLANE_LANE
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane test_iOS # $FASTLANE_LANE
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

  # adhoc:
  #   macos:
  #     xcode: 13.4.1
  #   environment:
  #     FL_OUTPUT_DIR: output
  #     FASTLANE_LANE: adhoc
  #   steps:
  #     - checkout
  #     - run: bundle install
  #     - run:
  #         name: Fastlane
  #         command: bundle exec fastlane $FASTLANE_LANE
  #     - store_artifacts:
  #         path: output

workflows:
  build-and-test:
    jobs:
      - swiftlint
      - build-and-test
      # - adhoc:
      #     filters:
      #       branches:
      #         only: development
      #     requires:
      #       - build-and-test
